### ISSUE TITLE
Connects but No Internet

### ISSUE THREAD

**Issue by parsalotfy** [RattyDAVE/alpine-vpn-pptp#1]
Hi, 
I have done the instruction, the VPN connects successfully but there is no internet.
What should I do ?

**Comment by RattyDAVE** [comment]
Hi.

What are the parameters you are using? 
What is the Host OS?

What is the command line you are running?
```
docker run -d --name VPN --restart unless-stopped --privileged --net=host \
           -v {local_path_to_chap_secrets}:/etc/ppp/chap-secrets \
           rattydave/alpine-vpn-pptp
```

**Comment by parsalotfy** [comment]
I'm sorry it's not your fault, I found out my government bans PPTP on Hetzner datacenter....
good luck.

**Comment by fozbek** [comment]
> I'm sorry it's not your fault, I found out my government bans PPTP on Hetzner datacenter....
> good luck.

You can try Scaleway. Stardust instances are very cheap
